# Generated by Django 5.2.8 on 2025-12-01 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="category",
            new_name="products_ca_slug_da4386_idx",
            old_name="products_ca_slug_idx",
        ),
        migrations.RenameIndex(
            model_name="category",
            new_name="products_ca_is_acti_a2d000_idx",
            old_name="products_ca_is_act_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_seller__2449b8_idx",
            old_name="products_pr_seller__idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_categor_75eeb5_idx",
            old_name="products_pr_categor_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_status_041708_idx",
            old_name="products_pr_status_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_created_bce1a7_idx",
            old_name="products_pr_created_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_price_9b1a5f_idx",
            old_name="products_pr_price_idx",
        ),
    ]
